# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_year', models.IntegerField()),
                ('_tag_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=300)),
                ('_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(default=None, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.AcademicYear')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_first_name', models.CharField(max_length=100)),
                ('_last_name', models.CharField(max_length=100)),
                ('_date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Department')),
                ('_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Period')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAllotted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Lecturer')),
                ('_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='lecturer',
            name='_is',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Staff'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='_department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.Department'),
        ),
    ]
